from dotenv import load_dotenv
load_dotenv()
from werkzeug.security import generate_password_hash

from backend import app, db
from backend.models import User, Camera, Image

with app.app_context():
  db.drop_all()
  db.create_all()

  demo = User(username = 'Demo', email = 'demo@demo.com', hashed_password = generate_password_hash("password"))


  D3500 = Camera(id = 1, title = 'Nikon D3500', brand = 'Nikon', type = 'DSLR', description = '24.2MP DX-Format CMOS Sensor AF-P DX 18-55mm f/3.5-5.6G VR Lens AF-P DX 70-300mm f/4.5-6.3G ED Lens Native ISO 100-25600; 5 fps 3.0" 921k-Dot LCD Monitor HD 1080p Video Recording at 60 fps Multi-CAM 1000 11-Point AF System', price = 849.00, quantity=10)
  D3500_photo_1 = Image(camera_id = 1, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=459720")
  D3500_photo_2 = Image(camera_id = 1, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=459722")
  D3500_photo_3 = Image(camera_id = 1, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=459723")
  db.session.add(D3500)
  db.session.add(D3500_photo_1)
  db.session.add(D3500_photo_2)
  db.session.add(D3500_photo_3)
  D3600 = Camera(id = 2, title = 'Nikon D5600', brand = 'Nikon', type = 'SLR', description = "Large, 24.2 MP DX-format CMOS sensor Always connected to your smart device with SnapBridge 3.2-inch Vari-angle touch LCD Advanced 39-point Auto Focus system Full HD 1080 at 60p video capability with built-in stereo sound", price = 799.95, quantity=10)
  D3600_photo_1 = Image(camera_id = 2, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=301085")
  D3600_photo_2 = Image(camera_id = 2, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=301087")
  D3600_photo_3 = Image(camera_id = 2, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=301088")
  db.session.add(D3600)
  db.session.add(D3600_photo_1)
  db.session.add(D3600_photo_2)
  db.session.add(D3600_photo_3)
  B500 = Camera(id = 3, title = 'Nikon COOLPIX B500', brand = 'Nikon', type = 'Optical', description = "40x optical zoom/80x Dynamic Fine Zoom Built-in Wi-Fi Shoot from creative angles with the tilting 3.0-inch 921,000-dot LCD Simple, convenient operation for stress-free shooting", price = 299.95, quantity=10)
  B500_photo_1 = Image(camera_id = 3, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=188951")
  B500_photo_2 = Image(camera_id = 3, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=188957")
  B500_photo_3 = Image(camera_id = 3, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=188958")
  db.session.add(B500)
  db.session.add(B500_photo_1)
  db.session.add(B500_photo_2)
  db.session.add(B500_photo_3)
  Z7II = Camera(id = 4, title = 'Nikon Z7II', brand = 'Nikon', type = 'Mirrorless', description = "Ultra High Resolution 45.7MP CMOS Sensor 4K UHD Video at 60p Dual EXPEED 6 Processors for Twice the Power 493-point Hybrid AF & Eye Detect AF 5-Axis VR Image Stabilization Dual Card Slots Intuitive Interface Weather Sealing", price = 3596.95, quantity=10)
  Z7II_photo_1 = Image(camera_id = 4, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=626432")
  Z7II_photo_2 = Image(camera_id = 4, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=626497")
  Z7II_photo_3 = Image(camera_id = 4, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=626433")
  db.session.add(Z7II)
  db.session.add(Z7II_photo_1)
  db.session.add(Z7II_photo_2)
  db.session.add(Z7II_photo_3)
  P900 = Camera(id = 5, title = 'Nikon COOLPIX P900', brand = 'Nikon', type = 'Optical', description = "16MP CMOS Sensor. 83x Opt Zoom NIKKOR Super ED VR Lens. 24-2000mm 35mm Equivalent Focal Length. 3-inch LCD. Optical VR Image Stabilization System. Full HD 1080/60p Video. Built-In Wi-Fi, GPS, and NFC.", price = 699.00, quantity=10)
  P900_photo_1 = Image(camera_id = 5, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=169173")
  P900_photo_2 = Image(camera_id = 5, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=169172")
  P900_photo_3 = Image(camera_id = 5, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=169171")
  db.session.add(P900)
  db.session.add(P900_photo_1)
  db.session.add(P900_photo_2)
  db.session.add(P900_photo_3)
  a7III = Camera(id = 6, title = 'Sony a7III', brand = 'Sony', type = 'Mirrorless', description = "24.2MP 35mm full-frame back-illuminated CMOS sensor Sensitivity range up to ISO 51200 Fast Hybrid AF with 693 phase and 425 contrast detection points High-speed continuous shooting up to 10fps 4K HDR movie recording capability", price = 2199.99, quantity=10)
  a7III_photo_1 = Image(camera_id = 6, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=345411")
  a7III_photo_2 = Image(camera_id = 6, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=345429")
  a7III_photo_3 = Image(camera_id = 6, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=345419")
  db.session.add(a7III)
  db.session.add(a7III_photo_1)
  db.session.add(a7III_photo_2)
  db.session.add(a7III_photo_3)
  a7c = Camera(id = 7, title = 'Sony a7C', brand = 'Sony', type = 'Mirrorless', description = "The World’s Smallest and Lightest Full-frame Camera - without compromise. 24.2MP Backside Illuminated 35mm Sensor 4K Movie w/ Full-Pixel Readout Flip-out LCD 5-Axis IBIS In-Body Image Stabilization Ideal for On The Go & Vlogging", price = 2098.00, quantity=10)
  a7c_photo_1 = Image(camera_id = 7, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=621084")
  a7c_photo_2 = Image(camera_id = 7, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=621083")
  a7c_photo_3 = Image(camera_id = 7, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=621085")
  db.session.add(a7c)
  db.session.add(a7c_photo_1)
  db.session.add(a7c_photo_2)
  db.session.add(a7c_photo_3)
  a7c = Camera(id = 8, title = 'Sony Alpha a7II', brand = 'Sony', type = 'Mirrorless', description = "FE 28-70mm F3.5-5.6 OSS included, World's first full-frame camera with 5-axis image stabilization, Enhanced Fast Hybrid AF, 24.3MP 35mm full-frame Exmor CMOS sensor, BIONZ X image processing engine, High 50Mbps bit-rate XAVC S format recording", price = 2098.00, quantity=10)
  a7c_photo_1 = Image(camera_id = 8, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=69354")
  a7c_photo_2 = Image(camera_id = 8, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=69358")
  a7c_photo_3 = Image(camera_id = 8, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=69355")
  db.session.add(a7c)
  db.session.add(a7c_photo_1)
  db.session.add(a7c_photo_2)
  db.session.add(a7c_photo_3)
  RX100 = Camera(id = 9, title = 'Sony RX100 VI Cyber-shot', brand = 'Sony', type = 'Optical', description = "Be ready to take on the world. This pocket-size compact comes with no-compromise high-zoom performance and super-fast AF, so you can capture every opportunity that comes your way - just the way you want - and fully unleash your creative self-expression.", price = 1198.00, quantity=10)
  RX100_photo_1 = Image(camera_id = 9, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=371341")
  RX100_photo_2 = Image(camera_id = 9, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=371344")
  RX100_photo_3 = Image(camera_id = 9, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=371343")
  db.session.add(RX100)
  db.session.add(RX100_photo_1)
  db.session.add(RX100_photo_2)
  db.session.add(RX100_photo_3)
  a7RII = Camera(id = 10, title = 'Sony a7R II', brand = 'Sony', type = 'Mirrorless', description = "Back-illuminated full-frame CMOS 42.4 MP sensor High-speed BIONZ X image processing engine Higher-resolution 4K movie recording 5-axis image stabilization XGA OLED Tru-Finder PlayMemories Camera Apps Wi-Fi / NFC", price = 3199.99, quantity=10)
  a7RII_photo_1 = Image(camera_id = 10, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=85757")
  a7RII_photo_2 = Image(camera_id = 10, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=85760")
  a7RII_photo_3 = Image(camera_id = 10, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=85762")
  db.session.add(a7RII)
  db.session.add(a7RII_photo_1)
  db.session.add(a7RII_photo_2)
  db.session.add(a7RII_photo_3)
  EOS_1D = Camera(id = 11, title = 'Canon EOS-1D X Mark III', brand = 'Canon', type = 'SLR', description = "20.1 Megapixel Full-Frame CMOS Sensor NEW DIGIC X Image Processor ISO Range of 100-102400 Dual Pixel CMOS AF", price = 6499.00, quantity=10)
  EOS_1D_photo_1 = Image(camera_id = 11, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=565952")
  EOS_1D_photo_2 = Image(camera_id = 11, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=565951")
  EOS_1D_photo_3 = Image(camera_id = 11, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=565953")
  db.session.add(EOS_1D)
  db.session.add(EOS_1D_photo_1)
  db.session.add(EOS_1D_photo_2)
  db.session.add(EOS_1D_photo_3)
  EOS_5D_Mark_IV = Camera(id = 12, title = 'Canon EOS 5D Mark IV', brand = 'Canon', type = 'DSLR', description = "Canon EOS 5D Mark IV 30.4MP DSLR Camera + EF 24-105mm Lens + BG-E21 Battery Grip", price = 3699.00, quantity=10)
  EOS_5D_Mark_IV_photo_1 = Image(camera_id = 12, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=493645")
  EOS_5D_Mark_IV_photo_2 = Image(camera_id = 12, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=493646")
  EOS_5D_Mark_IV_photo_3 = Image(camera_id = 12, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=493648")
  db.session.add(EOS_5D_Mark_IV)
  db.session.add(EOS_5D_Mark_IV_photo_1)
  db.session.add(EOS_5D_Mark_IV_photo_2)
  db.session.add(EOS_5D_Mark_IV_photo_3)
  EOSR6 = Camera(id = 13, title = 'Canon EOS R6 Full Frame', brand = 'Canon', type = 'Mirrorless', description = "New Full-Frame CMOS Sensor Image Sensor & DIGIC Processor 5-axis IBIS In-Body Image Stabilization High-Speed Shooting up to 20 fps 4K UHD recording at up to 60fps Dual Pixel CMOS AF II Vari-angle Touchscreen LCD Dual Card Slots", price = 3599.00, quantity=10)
  EOSR6_photo_1 = Image(camera_id = 13, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=606654")
  EOSR6_photo_2 = Image(camera_id = 13, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=606653")
  EOSR6_photo_3 = Image(camera_id = 13, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=606662")
  db.session.add(EOSR6)
  db.session.add(EOSR6_photo_1)
  db.session.add(EOSR6_photo_2)
  db.session.add(EOSR6_photo_3)
  EOSR  = Camera(id = 14, title = 'Canon EOS R Full Frame', brand = 'Canon', type = 'Mirrorless', description = "New Full-Frame 30.3MP 3.69m-Dot OLED Electronic Viewfinder Expanded ISO 50-102400, 8 fps Shooting 30.3MP Full-Frame CMOS Sensor UHD 4K30 Video; C-Log & 10-Bit HDMI Out 3.15 2.1m-Dot Swivel Touchscreen LCD RF 24-105mm f/4L IS USM Lens", price = 3399.00, quantity=10)
  EOSR_photo_1 = Image(camera_id = 14, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=396155")
  EOSR_photo_2 = Image(camera_id = 14, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=532305")
  EOSR_photo_3 = Image(camera_id = 14, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=396156")
  db.session.add(EOSR)
  db.session.add(EOSR_photo_1)
  db.session.add(EOSR_photo_2)
  db.session.add(EOSR_photo_3)
  EOS6D  = Camera(id = 15, title = 'Canon EOS 6D Mark II Full Frame', brand = 'Canon', type = 'DSLR', description = "26.2 Megapixel Full-frame CMOS Sensor. DIGIC 7 Image Processor, ISO 100-40000. Vari-angle Touch Screen, 3.0-inch LCD. Built-in Wi-Fi, NFC, Bluetooth and GPS. High-Speed Continuous Shooting at up to 6.5 fps. Dust- & Water-resistant.", price = 2199.00, quantity=10)
  EOS6D_photo_1 = Image(camera_id = 15, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=1200&picId=493677")
  EOS6D_photo_2 = Image(camera_id = 15, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=493678")
  EOS6D_photo_3 = Image(camera_id = 15, url_reference = "https://www.beachcamera.com/shop/product-image.aspx?size=500&picId=493681")
  db.session.add(EOS6D)
  db.session.add(EOS6D_photo_1)
  db.session.add(EOS6D_photo_2)
  db.session.add(EOS6D_photo_3)

  


  db.session.add(demo)
  db.session.commit()